# Generated by Django 5.1 on 2024-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_evento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='vagas_ilimitadas',
            field=models.BooleanField(default=False),
        ),
    ]
